name: optimisation-course
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pyomo=6.4.1
    - pandas=1.4.3
    - matplotlib=3.5.3
    - jupyterlab
    - glpk=5.0
    - ipopt=3.14.9
    - git  # Necessary on Windows for pip-installing from a git repository
    - pip
    - pip:
        - -e git+https://github.com/sjpfenninger/optimisation-course.git#egg=optimutils&subdirectory=optimutils
